### ISSUE TITLE
Maps without placeInitialArmies() prevent Viking teaming

### ISSUE THREAD

**Issue by Atelaes** [JohnMTorgerson/Viking#20]
The Global map has a starting scenario without placeInitialArmies.  Since the teaming is started in placeInitialArmies, Viking does not team in this situation.  Solution is probably to move teaming instantiation somewhere else.

**Comment by JohnMTorgerson** [comment]
This has since been solved. We now initiate teaming in 3 places, redundantly: pickCountry() (no announcement to the user), placeInitialArmies() (on the first placement only), and placeArmies() (on the first turn only). I'll mark this issue closed. The only thing really left to do here is streamline the announcements to the user. Right now it's possible for the user to be notified more than once that teaming is on. Not a huge deal, just a minor point.
